# -*- coding: utf-8 -*-
"""nn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppF-j7AB0BJnVeAdD3ZlnejCuQ7G0wMX
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from typing import Tuple, Dict


def create_income_earlystopping_and_noearlystopping_networks(n_inputs: int, n_outputs: int):
    """Creates two neural networks for income prediction: one with early stopping, one without."""

    # Model architecture
    def build_model():
        model = keras.Sequential([
            layers.Input(shape=(n_inputs,)),
            layers.Dense(256, activation='relu'),  # Increased neurons
            layers.Dense(128, activation='relu'),
            layers.Dense(64, activation='relu'),
            layers.Dense(n_outputs, activation='sigmoid')  # Binary classification
        ])
        model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
        return model

    early_model = build_model()
    late_model = build_model()

    # Early stopping callback with increased patience
    early_stopping = keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

    return early_model, {'callbacks': [early_stopping], 'epochs': 50}, late_model, {'epochs': 50}

